encryptionsalt: v1:uBVZwH4YnaM=:v1:7pKFYUnmiVk3DLLu:vUpuvbKtwmOFMdODg/3WEBtarrxC9w==
config:
  azure-native:location: eastus2
  catalog:nameSuffix: "654964"
  catalog:sqlAdminLogin: catalogsqladmin
  catalog:sqlDatabaseSku: Basic
  catalog:sqlAdminPassword:
    secure: v1:n/kPY8ODlgVMHT6z:qf29fEgyplgzTsRJStwKOkBv4UIyPO01d9rDJsR1tXxa45HtHcg6/a1aAZ8fSsOWngPXCcjThK9R6GR1DN644Q==
  catalog:deployWorkload: "true"
  catalog:sqlLocation: centralus
  catalog:costProfile: poc-free
  catalog:allowPaidResources: "false"
  catalog:sqlUseFreeOffer: "false"
  catalog:budgetContactEmail: emanuelabr22@gmail.com
  catalog:budgetAmountUsd: "10"
  catalog:apiImage: ghcr.io/agentflow-sdlc/catalog-api:31196570338-3be933568b9d
  catalog:migratorImage: ghcr.io/agentflow-sdlc/catalog-database-migrator:31196570338-3be933568b9d
