encryptionsalt: v1:gPvVls4nk/o=:v1:jhwYjJk5wCib8msu:4rgAiVZVpMjYEXfzAnDZQ+XFMiU1XQ==
config:
  azure-native:location: eastus2
  catalog:nameSuffix: "654964"
  catalog:sqlAdminLogin: catalogsqladmin
  catalog:sqlDatabaseSku: Basic
  catalog:sqlAdminPassword:
    secure: v1:B0eEVAT2Xh9Bfpka:P6XXvcvOdJHrmg9acP2NvKnqPo37Q3++h53jzeloZvZnzbJ1lQ8OvBK03Nl3gc3a5pmjTRVDleM=
  catalog:deployWorkload: "true"
  catalog:sqlLocation: centralus
  catalog:costProfile: poc-free
  catalog:allowPaidResources: "false"
  catalog:sqlUseFreeOffer: "true"
  catalog:budgetContactEmail: emanuelabr22@gmail.com
  catalog:budgetAmountUsd: "10"
  catalog:apiImage: ghcr.io/agentflow-sdlc/catalog-api:31196570338-3be933568b9d
  catalog:migratorImage: ghcr.io/agentflow-sdlc/catalog-database-migrator:31196570338-3be933568b9d
