<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <AssemblyName>Catalog.Api.Tests</AssemblyName>
    <RootNamespace>Catalog.Api.Tests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Microsoft.OpenApi" />
    <PackageReference Include="Microsoft.OpenApi.YamlReader" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Catalog.Api\Catalog.Api.csproj" />
    <ProjectReference Include="..\..\src\Catalog.Contracts\Catalog.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\..\openapi\catalog-api.yaml">
      <Link>openapi\catalog-api.yaml</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>
</Project>
